

TOP_DIR = $(realpath ../../ee477-hammer-cad)
OBJ_DIR = build
INPUT_CFGS =cfg/bsg_mesh_router_cfg.yml cfg/bsg_mesh_router_src.yml
TB_CFGS = cfg/bsg_mesh_router_tb.yml

include $(TOP_DIR)/module_top.mk
